displayName=Wheelbound
author=TheRealEddieDean
support=https://github.com/TheRealEddieDean/RunlitePLugin-Wheelbound/issues
description=Choose a boss, skill or unfinished Combat Achievement encounter with configurable icon wheels.
tags=wheel,randomizer,bossing,skilling,combat achievements
plugins=com.wheelbound.WheelboundPlugin
