displayName=Wheelbound
author=TheRealEddieDean
support=https://github.com/TheRealEddieDean/RunlitePLugin-Wheelbound/issues
description=Spin for your next boss, skill, quest, pet hunt or unfinished Combat Achievement encounter, or create your own custom wheels.
tags=wheel,randomizer,bossing,skilling,combat achievements,pets,quests,custom
plugins=com.wheelbound.WheelboundPlugin
version=1.0.0
build=standard
